variables:
  HELM_CHART_PATH: ./helm/app
  CI_PROJECT_NAME: nms-frontend
  CI_REGISTRY_IMAGE: "${HARBOR_HOST}/${HARBOR_PROJECT}/${CI_PROJECT_NAME}"
  GITLAB_ADVANCED_SAST_ENABLED: "true"
  FF_TIMESTAMPS: true

cache:
  paths:
    - .m2/repository
    - target/

stages:
  - build
  - deploy-dev
  - deploy-uat
  - deploy-prod
  - test

include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

build:
  stage: build
  tags:
    - k8s
  environment: dev
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${HARBOR_HOST}\":{\"auth\":\"$(echo -n ${HARBOR_USERNAME}:${HARBOR_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${HARBOR_HOST}/${HARBOR_PROJECT}/${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}"
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^dev/ || $CI_COMMIT_BRANCH =~ /^release/

deploy-dev:
  stage: deploy-dev
  tags:
    - k8s
  environment: dev
  image:
    name: alpine/helm:latest
    entrypoint: [""]
  script:
    - helm upgrade --install
      -n nms-test --create-namespace
      -f $HELM_CHART_PATH/values.dev.yaml
      nms-frontend $HELM_CHART_PATH
      --set deployments[0].image=${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^dev/
#deploy-uat:
#  stage: deploy-uat
#  tags:
#    - nms-uat-k8s
#  environment: uat
#  image:
#    name: alpine/helm:latest
#    entrypoint: [""]
#  script:
#    #-  helm uninstall --debug nms-uat -n nms-uat --no-hooks
#    -  export KUBECONFIG=/etc/rancher/rke2/rke2.yaml;
#       helm upgrade --install
#      -n nms-uat --create-namespace
#      -f $HELM_CHART_PATH/values.uat.yaml
#      nms-uat $HELM_CHART_PATH
#  rules:
#  - if:  $CI_COMMIT_TAG =~ /^uat/

#deploy-prod:
#  stage: deploy-prod
#  tags:
#    - nms-uat-k8s
#  environment: prod
#  image:
#    name: alpine/helm:latest
#    entrypoint: [""]
#  script:
#    #-  helm uninstall --debug nms-prod -n nms-prod --no-hooks
#    -  helm delete nms-prod --namespace nms-prod
#    -  export KUBECONFIG=/etc/rancher/rke2/rke2.yaml;
#       helm upgrade --install
#      -n nms-prod --create-namespace
#      -f $HELM_CHART_PATH/values.prod.yaml
#      nms-prod $HELM_CHART_PATH
#  rules:
#  - if:  $CI_COMMIT_TAG =~ /^prod/

