services:
  app:
    image: maven:3.8.5-openjdk-8
    container_name: sumfood_backend
    working_dir: /app
    volumes:
      - ./sumfood-backend:/app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: mvn spring-boot:run

  frontend:
    image: node:23-bookworm
    working_dir: /app
    container_name: sumfood_frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./sumfood-frontend/app:/app
    command: |
      sh -c "npm ci && npm start"

  db:
    container_name: sumfood_db
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ../data/pg_data:/var/lib/postgresql/data
    ports:
      - "5446:5432"